### PR TITLE
Frontend better starter :rocket:

### PR DESCRIPTION
**Pull request by styczynski**
This PR provides us with a clean base to start development:

* Configured Typescript
* Configured Jest
* Documentation and coverage reported to HTML
* Uses Styled Components
* Uses Polyglot for translation features
* Implemented basic UI components i.e. side menu, buttons, page view, dashboard simple view
* Updated readme

### CODE REVIEW

**Comment by mbalc** [comment]
pipeline doesn't pass, fix plx

**Comment by styczynski** [comment]
@mbalc That was an issue with Docker path to frontend dist. I changed it and forgot about setting correct Docker variable. It's fixed now.

Anyway, there's some mess with commits for now - I used templated styling files for code-based docs generation and that is pretty large stuff. I removed also an existing starter as it didn't provide support for TS and another tooling. It may be a review pain, but all the rest is pretty fine.

**Comment by mbalc** [comment]
@styczynski would it be possible to split up this PR so those changes that are reviewable are in one diff and all automatica changes are in another one?

**Comment by mbalc** [comment]
remember you can point PRs to other branches than master afaik

**Comment by mbalc** [comment]
so that should be possible to do provided that automatic ones are in separate commits

**Comment by styczynski** [comment]
@mbalc 
As I noticed only the first commit "Provide typescript support and generate docs with istanbul and typedoc" it containing trash diffs like removing old template and providing docs resources like stylings etc. and there are breaking changes that make other commits dependant on that. I would recommend reviewing it anyway, but skipping the "trash" from that commit.

**Comment by styczynski** [comment]
This PR will be closed in favour of #30 and #31 (suggestion of @mbalc)

**Pull request closed without merging**
